apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: appsso-starter-java-1
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
  name: appsso-starter-java-1
spec:
  params:
    - name: live-update
      value: "true"
  serviceClaims:
    - name: appsso-starter-java
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: appsso-starter-java
  source:
    git:
      url: https://github.com/jlafata/appsso-starter-java.git
      ref:
        branch: main
